FROM node:22-alpine AS build-stage

WORKDIR /usr/app
COPY . .

RUN npm ci
RUN npm build
RUN npm lint
RUN npm test

FROM nginx:stable-alpine AS production-stage

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build-stage /usr/app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
